coverage:
  status:
    project:
      default:
        # non-blocking checks
        informational: true
        target: auto
        # allow a 1% drop from the previous base commit coverage (for exception handling in download)
        threshold: 1%
    patch:
      default:
        # non-blocking checks
        informational: true
  
ignore:
 - ml4co_kit/learning/**
 - ml4co_kit/extension/**
 - ml4co_kit/solver/gurobi.py
 - ml4co_kit/solver/lib/gurobi/**
 - ml4co_kit/utils/env_utils.py